### PR TITLE
chore: Add GitHub Actions to dependabot

### PR DESCRIPTION
**Pull request by lucacome**
## Pull request description 

Most of the GitHub Actions seem to be out of date. Use dependabot to keep them up to date.

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

**Comment by lucacome** [comment]
I'm not sure if the PRs should target `main`. I see that the option is set for `gomod` but it seems like `develop` is the default branch and I couldn't find anything in the docs that explains the difference between `main` and `develop`.

**Review by vsukhin — APPROVED** [review]
thank you @lucacome  looks good to me, @ypoplavs ?

**Comment by lucacome** [comment]
> we release from main, develop is for implemented features

so should the `gomod` section be changed to target `develop` as well?

**Comment by lucacome** [comment]
@vsukhin let me know if there's anything I need to do

**Comment by vsukhin** [comment]
thank you, @lucacome! merged

**Pull request merged**
