### PR TITLE
feat: add labels to test and job

### LINKED ISSUE #3270: The test type is automatically added as a label to Test/suite definitions

### PR DESCRIPTION
**Pull request by vsukhin**
## Pull request description 

Fixes #3270, #3478  

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [x] tested locally
- [x] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [x] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

**Review by nicufk — APPROVED** [review]

**Review by vLia — APPROVED** [review]

**Comment by AndrewUnderwoodAtFanatics** [comment]
@vsukhin I've upgraded to version `1.11.64` of the helm chart but I'm not seeing any new labels in the job or pod created by testkube.  Is there something additional I need to do?

image

**Comment by AndrewUnderwoodAtFanatics** [comment]
For clarity, I'm on `testkube-api-server:1.11.3`

**Comment by vsukhin** [comment]
Why? On you screen executor=k6-executor, test-type=k6-script

**Comment by AndrewUnderwoodAtFanatics** [comment]
My impression from https://github.com/kubeshop/testkube/issues/3478 was that this feature would also propagate the test name through to the job and pod specs.

So for example, if my test was called `login-load-test`

```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: login-load-test
  namespace: testkube
```

Then the jobs and pods would have a label like `test-name=login-load-test`.  Having the test name on the executor pod makes it easier to track the cpu/memory/etc usage of the executor pod along side the other data the test puts out.

**Pull request merged**
