### PR TITLE
feat: add spinner to testkube init

### PR DESCRIPTION
**Pull request by Sindhuinti**
## Pull request description 

Add spinner animation while installing the helm charts by using `testkube init` command

## Checklist (choose whats happened)

- [✅] tested locally
- [✅] tested on cluster
- [✅] added new dependencies

## Changes

demo

## Fixes

- #3752

### CODE REVIEW

**Review by vsukhin — APPROVED** [review]
looks good! thank you, @Sindhuinti

**Comment by Sindhuinti** [comment]
Hey @exu @nicufk @vLia @povilasv @dejanzele
Please review this PR

**Comment by vsukhin** [comment]
hey @Sindhuinti can you please check compilation errors?

**Comment by Sindhuinti** [comment]
@vsukhin I am getting error for unit tests. Could you please help me with that?

**Comment by vsukhin** [comment]
sounds like you need to add "time" import into cmd/kubectl-testkube/commands/common.go

**Comment by Sindhuinti** [comment]
Done @vsukhin

**Review by vLia — APPROVED** [review]
Looks good, well done 👍

**Comment by vsukhin** [comment]
one small improvement run `go fmt` in cmd/kubectl-testkube/commands folder

**Comment by Sindhuinti** [comment]
> one small improvement run `go fmt` in cmd/kubectl-testkube/commands folder

Done 👍🏻 @vsukhin

**Review by vsukhin — APPROVED** [review]

**Pull request merged**
